/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/captcha/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取前端验证码服务配置。 */
        get: operations["getCaptchaConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注册用户账号。
         * @description 与现有注册行为保持一致：
         *     - 首个注册用户获得 `Admin` 权限。
         *     - 后续用户默认获得 `None` 权限。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录并创建认证会话。 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出当前会话。 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前已认证用户信息。 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按认证状态列出设备。 */
        get: operations["listDevices"];
        put?: never;
        /** 预创建设备并分配 MQTT 连接令牌。 */
        post: operations["createDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取设备详情。 */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /** 永久删除设备及其关联数据。 */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 审批待认证设备。 */
        post: operations["approveDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 拒绝待认证设备或撤销已认证设备。 */
        post: operations["revokeDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将设备从已拒绝/已撤销状态移回待认证状态。 */
        post: operations["unblockDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新设备令牌。 */
        post: operations["refreshDeviceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将下行指令推入设备发送队列。 */
        post: operations["enqueueDeviceCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询设备指标点数据。 */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access-control/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询设备门禁模块状态。
         * @description 读取设备最近一次门禁输入信号：
         *     - legacy metric type `8` 表示 `signal_a`
         *     - legacy metric type `16` 表示 `signal_b`
         *     - 当 `signal_a == 1 && signal_b == 1` 时，判定为开门。
         */
        get: operations["getAccessControlState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出账号。
         * @description 当前租户的 `tenant_admin` 可访问。返回系统账号列表，并附带账号在当前租户下的成员角色（如存在）。
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出当前账号收到的待处理租户邀请。
         * @description 返回当前登录账号尚未处理且未过期的租户邀请。
         */
        get: operations["listPendingTenantInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{invitation_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 接受租户邀请。
         * @description 仅邀请接收账号本人可接受该邀请。接受成功后账号会加入邀请对应租户。
         */
        post: operations["acceptTenantInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{invitation_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 拒绝租户邀请。
         * @description 仅邀请接收账号本人可拒绝该邀请。
         */
        post: operations["rejectTenantInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出当前账号可访问的租户。
         * @description 账号可以加入多个租户。普通账号只返回自己加入的租户；当前租户 `tenant_admin` 可用于租户管理界面。
         */
        get: operations["listTenants"];
        put?: never;
        /**
         * 创建新租户。
         * @description 已认证账号可创建新租户；创建者会自动成为该租户的 `tenant_admin`。
         */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取租户详情。 */
        get: operations["getTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 更新租户信息。
         * @description 仅该租户的 `tenant_admin` 可更新租户主档。
         */
        patch: operations["updateTenant"];
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出租户用户。
         * @description 返回指定租户的所有账号及其角色。仅该租户的 `tenant_admin` 可访问。
         */
        get: operations["listTenantUsers"];
        put?: never;
        /**
         * 邀请用户加入租户。
         * @description 创建租户邀请并分配目标租户角色；用户接受邀请后才会成为租户成员。
         *     仅该租户的 `tenant_admin` 可操作。
         */
        post: operations["inviteTenantUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 创建租户邀请。
         * @description 创建租户邀请。仅该租户的 `tenant_admin` 可操作。
         *     该接口与 `POST /api/v1/tenants/{tenant_id}/users` 的邀请语义一致，
         *     但响应体直接返回创建出的邀请对象。
         */
        post: operations["createTenantInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 从租户移除用户。
         * @description 仅该租户的 `tenant_admin` 可操作。
         */
        delete: operations["removeTenantUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出设备分组。
         * @description 返回当前租户下的所有设备分组。
         */
        get: operations["listDeviceGroups"];
        put?: never;
        /**
         * 创建设备分组。
         * @description 在当前租户下创建新的设备分组。
         */
        post: operations["createDeviceGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取分组详情。 */
        get: operations["getDeviceGroup"];
        put?: never;
        post?: never;
        /** 删除设备分组。 */
        delete: operations["deleteDeviceGroup"];
        options?: never;
        head?: never;
        /** 更新分组信息。 */
        patch: operations["updateDeviceGroup"];
        trace?: never;
    };
    "/api/v1/groups/{group_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出分组内的设备。 */
        get: operations["listGroupDevices"];
        put?: never;
        /** 添加设备到分组。 */
        post: operations["addDeviceToGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}/devices/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 从分组移除设备。 */
        delete: operations["removeDeviceFromGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseBase: {
            /**
             * @description 0 表示成功，非 0 表示错误。
             * @example 0
             */
            code: number;
            /** @example ok */
            message: string;
            /**
             * @description 用于链路追踪的关联 ID。
             * @example req_20260312_abcdef
             */
            request_id: string;
            /** @description 可扩展元数据。 */
            meta?: {
                [key: string]: unknown;
            };
        };
        ErrorDetail: {
            /** @example validation_error */
            type: string;
            field?: string | null;
            reason?: string | null;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: components["schemas"]["ApiResponseBase"] & {
            data?: null;
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * @description 0=无权限, 1=只读, 2=读写, 3=管理员
         * @enum {integer}
         */
        PermissionType: 0 | 1 | 2 | 3;
        /**
         * @description 0=已认证, 1=已拒绝, 2=待认证, 3=未知, 4=已撤销
         * @enum {integer}
         */
        AuthStatusType: 0 | 1 | 2 | 3 | 4;
        /**
         * @description 0=离线, 1=在线, 2=延迟
         * @enum {integer}
         */
        DeviceRuntimeStatus: 0 | 1 | 2;
        /**
         * @description 1=温度, 2=湿度, 4=光照, 8=门禁输入信号A, 16=门禁输入信号B
         * @enum {integer}
         */
        MetricType: 1 | 2 | 4 | 8 | 16;
        CaptchaConfig: {
            /** @enum {string} */
            provider: "none" | "turnstile";
            enabled: boolean;
            site_key?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        CaptchaConfigResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["CaptchaConfig"];
        };
        RegisterRequest: {
            username: string;
            password: string;
            /** Format: email */
            email?: string | null;
            captcha_token?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            username: string;
            password: string;
            /** @default false */
            remember_me: boolean;
            captcha_token?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        AuthSession: {
            username: string;
            email?: string | null;
            /** @description 当前租户角色派生出的有效权限：tenant_ro=1，tenant_rw=2，tenant_admin=3。 */
            permission: components["schemas"]["PermissionType"];
            /** @description 当前生效租户下的账号角色。 */
            current_role?: components["schemas"]["TenantRole"];
            /** @description 当前生效租户（由 `X-Tenant-Id` 或服务端默认策略解析）。 */
            active_tenant?: string;
            /** @description 账号加入的所有租户及其角色。 */
            tenant_roles?: {
                [key: string]: components["schemas"]["TenantRole"];
            };
            /** @default true */
            authenticated: boolean;
            extensions?: {
                [key: string]: unknown;
            };
        };
        AuthSessionResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["AuthSession"];
        };
        DeviceMetadata: {
            name: string;
            hw_version: string;
            sw_version: string;
            config_version: string;
            sn: string;
            mac: string;
            /** Format: date-time */
            created_at: string;
            token?: string | null;
            authenticate_status: components["schemas"]["AuthStatusType"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceRuntime: {
            status?: components["schemas"]["DeviceRuntimeStatus"];
            /** @enum {string} */
            status_text?: "offline" | "online" | "delayed";
            /** Format: int64 */
            last_seen_ms?: number | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceRecord: {
            uuid: string;
            meta: components["schemas"]["DeviceMetadata"];
            runtime?: components["schemas"]["DeviceRuntime"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        PageMeta: {
            page: number;
            size: number;
            returned: number;
            total?: number | null;
            has_next?: boolean | null;
        };
        DeviceListData: {
            items: components["schemas"]["DeviceRecord"][];
            page: components["schemas"]["PageMeta"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceListResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["DeviceListData"];
        };
        DeviceDetailResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["DeviceRecord"];
        };
        CreateDeviceRequest: {
            name: string;
            hw_version?: string | null;
            sw_version?: string | null;
            config_version?: string | null;
            /** @description SN 与 MAC 至少提供一个，用于生成稳定设备 UUID。 */
            sn?: string | null;
            /** @description SN 与 MAC 至少提供一个，用于生成稳定设备 UUID。 */
            mac?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        ProvisionedMQTTCredentials: {
            /** @description MQTT client_id，等于设备 UUID。 */
            client_id: string;
            /** @description MQTT username，等于设备 UUID。 */
            username: string;
            /** @description MQTT password，等于设备 token。 */
            password: string;
            telemetry_topic: string;
            heartbeat_topic: string;
            downlink_topic: string;
            extensions?: {
                [key: string]: unknown;
            };
        };
        ProvisionedDeviceData: {
            uuid: string;
            tenant_id: string;
            token: string;
            mqtt: components["schemas"]["ProvisionedMQTTCredentials"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        ProvisionedDeviceResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["ProvisionedDeviceData"];
        };
        ActionResult: {
            /** @example approve_device */
            action: string;
            /** @example 07f5e... */
            target: string;
            /** @default true */
            success: boolean;
            /** @description 审批通过时返回新生成的设备 token。 */
            token?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        ActionResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["ActionResult"];
        };
        RefreshTokenData: {
            uuid: string;
            token: string;
            /** Format: date-time */
            rotated_at?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        RefreshTokenResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["RefreshTokenData"];
        };
        /**
         * @description 设备下行指令名称。
         * @enum {string}
         */
        DeviceCommandName: "config_push" | "ota_data" | "action_exec" | "screen_wy";
        /**
         * @description 设备下行指令状态。
         * @enum {string}
         */
        DeviceCommandStatus: "queued" | "sent" | "acked" | "failed";
        DeviceCommandRequest: {
            command: components["schemas"]["DeviceCommandName"];
            /** @description 指令负载（原样转发给设备侧）。 */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        DeviceCommandEnqueueData: {
            /** Format: int64 */
            command_id: number;
            uuid: string;
            command: components["schemas"]["DeviceCommandName"];
            /**
             * @description 协议 CmdID 的十进制表示。
             * @example 515
             */
            cmd_id: number;
            status: components["schemas"]["DeviceCommandStatus"];
            /** Format: date-time */
            enqueued_at?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceCommandEnqueueResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["DeviceCommandEnqueueData"];
        };
        MetricPoint: {
            /**
             * Format: int64
             * @description Unix 时间戳（毫秒）。
             */
            ts: number;
            /** Format: float */
            value: number;
            type: components["schemas"]["MetricType"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        MetricsData: {
            uuid: string;
            /** @enum {string|null} */
            range?: "1h" | "6h" | "24h" | "7d" | "all" | null;
            /** Format: int64 */
            start_ms?: number | null;
            /** Format: int64 */
            end_ms?: number | null;
            points: components["schemas"]["MetricPoint"][];
            extensions?: {
                [key: string]: unknown;
            };
        };
        MetricsResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["MetricsData"];
        };
        AccessControlState: {
            uuid: string;
            /**
             * @description 门禁输入信号 A，最近指标值 >= 1 归一化为 1，否则为 0。
             * @enum {integer|null}
             */
            signal_a: 0 | 1 | null;
            /**
             * @description 门禁输入信号 B，最近指标值 >= 1 归一化为 1，否则为 0。
             * @enum {integer|null}
             */
            signal_b: 0 | 1 | null;
            /** @description 当 signal_a 与 signal_b 都为 1 时为 true；缺少任一信号时为 null。 */
            open: boolean | null;
            /**
             * Format: int64
             * @description 用于计算的最近信号时间戳（毫秒）。
             */
            evaluated_at_ms: number | null;
            /** @enum {string} */
            status_text: "open" | "closed" | "unknown";
            /** @description 当前门禁判定规则。 */
            rule?: string;
            extensions?: {
                [key: string]: unknown;
            };
        };
        AccessControlStateResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["AccessControlState"];
        };
        User: {
            username: string;
            /**
             * @deprecated
             * @description 兼容字段，表示当前租户角色派生出的有效权限；新实现应优先使用 `tenant_role`。
             */
            permission?: components["schemas"]["PermissionType"];
            /** @description 账号在当前租户下的角色；未加入当前租户时为空。 */
            tenant_role?: components["schemas"]["TenantRole"];
            /** Format: date-time */
            created_at: string;
            extensions?: {
                [key: string]: unknown;
            };
        };
        UserListData: {
            items: components["schemas"]["User"][];
            extensions?: {
                [key: string]: unknown;
            };
        };
        UserListResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["UserListData"];
        };
        /**
         * @description 租户角色：
         *     - tenant_admin: 租户管理员（可管理租户内用户和设备）
         *     - tenant_rw: 租户读写（可操作设备和数据）
         *     - tenant_ro: 租户只读（仅查看）
         * @enum {string}
         */
        TenantRole: "tenant_admin" | "tenant_rw" | "tenant_ro";
        /**
         * @description 租户状态：
         *     - active: 活跃
         *     - suspended: 暂停
         *     - archived: 归档
         * @enum {string}
         */
        TenantStatus: "active" | "suspended" | "archived";
        Tenant: {
            /** @description 租户 ID */
            id: string;
            /** @description 租户名称 */
            name: string;
            status: components["schemas"]["TenantStatus"];
            /** @description 当前账号在该租户下的角色；仅列表接口保证返回。 */
            role?: components["schemas"]["TenantRole"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            /** @description 租户元数据 */
            meta?: {
                [key: string]: unknown;
            };
        };
        TenantListResponse: components["schemas"]["ApiResponseBase"] & {
            data: {
                items: components["schemas"]["Tenant"][];
                total: number;
            };
        };
        TenantResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["Tenant"];
        };
        CreateTenantRequest: {
            /** @description 租户名称 */
            name: string;
            status?: components["schemas"]["TenantStatus"];
            meta?: {
                [key: string]: unknown;
            };
        };
        UpdateTenantRequest: {
            name?: string;
            status?: components["schemas"]["TenantStatus"];
            meta?: {
                [key: string]: unknown;
            };
        };
        TenantUser: {
            tenant_id: string;
            username: string;
            role: components["schemas"]["TenantRole"];
            /** Format: date-time */
            created_at: string;
        };
        TenantUserListResponse: components["schemas"]["ApiResponseBase"] & {
            data: {
                items: components["schemas"]["TenantUser"][];
                total: number;
            };
        };
        /**
         * @description 租户邀请状态：
         *     - pending: 待处理
         *     - accepted: 已接受
         *     - rejected: 已拒绝
         *     - expired: 已过期
         * @enum {string}
         */
        TenantInvitationStatus: "pending" | "accepted" | "rejected" | "expired";
        TenantInvitation: {
            /** @description 租户邀请 ID */
            id: string;
            /** @description 邀请加入的租户 ID */
            tenant_id: string;
            /** @description 被邀请账号用户名 */
            username: string;
            role: components["schemas"]["TenantRole"];
            /** @description 邀请发起账号用户名 */
            invited_by: string;
            status: components["schemas"]["TenantInvitationStatus"];
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TenantInvitationListData: {
            items: components["schemas"]["TenantInvitation"][];
            total: number;
        };
        TenantInvitationListResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["TenantInvitationListData"];
        };
        TenantInvitationResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["TenantInvitation"];
        };
        TenantInvitationActionResult: {
            /** @enum {string} */
            action: "accept" | "reject";
            /** @default true */
            success: boolean;
        };
        TenantInvitationActionResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["TenantInvitationActionResult"];
        };
        InviteTenantUserRequest: {
            username: string;
            role: components["schemas"]["TenantRole"];
        };
        /** @deprecated */
        AddTenantUserRequest: components["schemas"]["InviteTenantUserRequest"];
        InviteTenantUserResult: {
            /** @enum {string} */
            action: "invite_tenant_user";
            /** @description 被邀请账号用户名 */
            target: string;
            invitation: components["schemas"]["TenantInvitation"];
            /** @default true */
            success: boolean;
        };
        InviteTenantUserResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["InviteTenantUserResult"];
        };
        DeviceGroup: {
            /** @description 分组 ID */
            id: string;
            /** @description 所属租户 ID */
            tenant_id: string;
            /** @description 分组名称 */
            name: string;
            /** @description 分组描述 */
            description?: string | null;
            /** @description 设备数量 */
            device_count?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        DeviceGroupListResponse: components["schemas"]["ApiResponseBase"] & {
            data: {
                items: components["schemas"]["DeviceGroup"][];
                total: number;
                page: number;
                size: number;
            };
        };
        DeviceGroupResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["DeviceGroup"];
        };
        CreateDeviceGroupRequest: {
            /** @description 分组名称 */
            name: string;
            /** @description 分组描述 */
            description?: string | null;
        };
        UpdateDeviceGroupRequest: {
            name?: string;
            description?: string | null;
        };
        AddDeviceToGroupRequest: {
            /** @description 设备 UUID */
            uuid: string;
        };
    };
    responses: {
        /** @description 无效请求。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 需要认证或会话已过期。 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 权限不足。 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在。 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源已存在或状态冲突。 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        DeviceUUID: string;
        Username: string;
        /**
         * @description 认证状态筛选：
         *     - authenticated -> `AuthenticateStatus=0`
         *     - refused -> `AuthenticateStatus=1`
         *     - pending -> `AuthenticateStatus=2`
         *     - revoked -> `AuthenticateStatus=4`
         *     - all -> 不筛选
         */
        DeviceStatusFilter: "all" | "authenticated" | "pending" | "refused" | "revoked";
        Page: number;
        Size: number;
        MetricsRange: "1h" | "6h" | "24h" | "7d" | "all";
        /** @description 显式指定开始时间戳（毫秒）。与 `end_ms` 同时提供时会覆盖 `range`。 */
        StartMs: number;
        /** @description 显式指定结束时间戳（毫秒）。与 `start_ms` 同时提供时会覆盖 `range`。 */
        EndMs: number;
        /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
        TenantHeader: string;
        /** @description 设备分组过滤参数（当前阶段仅保留契约位，后续实现组级过滤）。 */
        GroupID: string;
        /** @description 租户 ID */
        TenantID: string;
        /** @description 租户邀请 ID */
        InvitationID: string;
        /** @description 设备分组 ID */
        GroupIDPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCaptchaConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 验证码配置。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaConfigResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功。 */
            200: {
                headers: {
                    /** @description 由服务端设置的会话 Cookie。 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已登出。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户信息。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: {
                /**
                 * @description 认证状态筛选：
                 *     - authenticated -> `AuthenticateStatus=0`
                 *     - refused -> `AuthenticateStatus=1`
                 *     - pending -> `AuthenticateStatus=2`
                 *     - revoked -> `AuthenticateStatus=4`
                 *     - all -> 不筛选
                 */
                status?: components["parameters"]["DeviceStatusFilter"];
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                /** @description 设备分组过滤参数（当前阶段仅保留契约位，后续实现组级过滤）。 */
                group_id?: components["parameters"]["GroupID"];
            };
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceRequest"];
            };
        };
        responses: {
            /** @description 设备已创建并返回连接凭据。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionedDeviceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    approveDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已通过审批。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销/已拒绝。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    unblockDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已解除阻断。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    refreshDeviceToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 令牌已刷新。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    enqueueDeviceCommand: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCommandRequest"];
            };
        };
        responses: {
            /** @description 指令已入队。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCommandEnqueueResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getMetrics: {
        parameters: {
            query?: {
                range?: components["parameters"]["MetricsRange"];
                /** @description 显式指定开始时间戳（毫秒）。与 `end_ms` 同时提供时会覆盖 `range`。 */
                start_ms?: components["parameters"]["StartMs"];
                /** @description 显式指定结束时间戳（毫秒）。与 `start_ms` 同时提供时会覆盖 `range`。 */
                end_ms?: components["parameters"]["EndMs"];
            };
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指标点数据。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAccessControlState: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 门禁模块状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlStateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 账号列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listPendingTenantInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 租户邀请列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantInvitationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    acceptTenantInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户邀请 ID */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 邀请已接受。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantInvitationActionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    rejectTenantInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户邀请 ID */
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 邀请已拒绝。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantInvitationActionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 租户列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description 租户已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID */
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 租户详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID */
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantRequest"];
            };
        };
        responses: {
            /** @description 租户已更新。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTenantUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID */
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 租户用户列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUserListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    inviteTenantUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID */
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteTenantUserRequest"];
            };
        };
        responses: {
            /** @description 邀请已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteTenantUserResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createTenantInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID */
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteTenantUserRequest"];
            };
        };
        responses: {
            /** @description 邀请已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantInvitationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    removeTenantUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID */
                tenant_id: components["parameters"]["TenantID"];
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户已移除。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listDeviceGroups: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备分组列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceGroupListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createDeviceGroup: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceGroupRequest"];
            };
        };
        responses: {
            /** @description 分组已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceGroupResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getDeviceGroup: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                /** @description 设备分组 ID */
                group_id: components["parameters"]["GroupIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分组详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceGroupResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDeviceGroup: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                /** @description 设备分组 ID */
                group_id: components["parameters"]["GroupIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分组已删除。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDeviceGroup: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                /** @description 设备分组 ID */
                group_id: components["parameters"]["GroupIDPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceGroupRequest"];
            };
        };
        responses: {
            /** @description 分组已更新。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceGroupResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listGroupDevices: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                /** @description 设备分组 ID */
                group_id: components["parameters"]["GroupIDPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分组设备列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListData"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    addDeviceToGroup: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                /** @description 设备分组 ID */
                group_id: components["parameters"]["GroupIDPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDeviceToGroupRequest"];
            };
        };
        responses: {
            /** @description 设备已添加。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removeDeviceFromGroup: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                /** @description 设备分组 ID */
                group_id: components["parameters"]["GroupIDPath"];
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备已移除。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
