/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/captcha/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get captcha provider config for frontend. */
        get: operations["getCaptchaConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register user account.
         * @description Mirrors existing register behavior:
         *     - First registered user gets `Admin` permission.
         *     - Later users default to `None` permission.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and create authenticated session. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current session. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user profile. */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices by auth status. */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get device details. */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /** Permanently delete device and related data. */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve pending device. */
        post: operations["approveDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject pending device or revoke authorized device. */
        post: operations["revokeDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move device from refused/revoked to pending. */
        post: operations["unblockDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh device token. */
        post: operations["refreshDeviceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query metric points for a device. */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List system users. */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{username}/permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update user permission level. */
        post: operations["updateUserPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseBase: {
            /**
             * @description 0 means success, non-zero means error.
             * @example 0
             */
            code: number;
            /** @example ok */
            message: string;
            /**
             * @description Correlation id for tracing.
             * @example req_20260312_abcdef
             */
            request_id: string;
            /** @description Extensible metadata. */
            meta?: {
                [key: string]: unknown;
            };
        };
        ErrorDetail: {
            /** @example validation_error */
            type: string;
            field?: string | null;
            reason?: string | null;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: components["schemas"]["ApiResponseBase"] & {
            data?: null;
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * @description 0=None, 1=ReadOnly, 2=ReadWrite, 3=Admin
         * @enum {integer}
         */
        PermissionType: 0 | 1 | 2 | 3;
        /**
         * @description 0=Authenticated, 1=Refused, 2=Pending, 3=Unknown, 4=Revoked
         * @enum {integer}
         */
        AuthStatusType: 0 | 1 | 2 | 3 | 4;
        /**
         * @description 0=Offline, 1=Online, 2=Delayed
         * @enum {integer}
         */
        DeviceRuntimeStatus: 0 | 1 | 2;
        /**
         * @description 1=Temperature, 2=Humidity, 4=Lux
         * @enum {integer}
         */
        MetricType: 1 | 2 | 4;
        CaptchaConfig: {
            /** @enum {string} */
            provider: "none" | "turnstile";
            enabled: boolean;
            site_key?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        CaptchaConfigResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["CaptchaConfig"];
        };
        RegisterRequest: {
            username: string;
            password: string;
            /** Format: email */
            email?: string | null;
            captcha_token?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            username: string;
            password: string;
            /** @default false */
            remember_me: boolean;
            captcha_token?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        AuthSession: {
            username: string;
            email?: string | null;
            permission: components["schemas"]["PermissionType"];
            /** @default true */
            authenticated: boolean;
            extensions?: {
                [key: string]: unknown;
            };
        };
        AuthSessionResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["AuthSession"];
        };
        DeviceMetadata: {
            name: string;
            hw_version: string;
            sw_version: string;
            config_version: string;
            sn: string;
            mac: string;
            /** Format: date-time */
            created_at: string;
            token?: string | null;
            authenticate_status: components["schemas"]["AuthStatusType"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceRuntime: {
            status?: components["schemas"]["DeviceRuntimeStatus"];
            /** @enum {string} */
            status_text?: "offline" | "online" | "delayed";
            /** Format: int64 */
            last_seen_ms?: number | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceRecord: {
            uuid: string;
            meta: components["schemas"]["DeviceMetadata"];
            runtime?: components["schemas"]["DeviceRuntime"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        PageMeta: {
            page: number;
            size: number;
            returned: number;
            total?: number | null;
            has_next?: boolean | null;
        };
        DeviceListData: {
            items: components["schemas"]["DeviceRecord"][];
            page: components["schemas"]["PageMeta"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceListResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["DeviceListData"];
        };
        DeviceDetailResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["DeviceRecord"];
        };
        ActionResult: {
            /** @example approve_device */
            action: string;
            /** @example 07f5e... */
            target: string;
            /** @default true */
            success: boolean;
            extensions?: {
                [key: string]: unknown;
            };
        };
        ActionResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["ActionResult"];
        };
        RefreshTokenData: {
            uuid: string;
            token: string;
            /** Format: date-time */
            rotated_at?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        RefreshTokenResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["RefreshTokenData"];
        };
        MetricPoint: {
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds.
             */
            ts: number;
            /** Format: float */
            value: number;
            type: components["schemas"]["MetricType"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        MetricsData: {
            uuid: string;
            /** @enum {string|null} */
            range?: "1h" | "6h" | "24h" | "7d" | "all" | null;
            /** Format: int64 */
            start_ms?: number | null;
            /** Format: int64 */
            end_ms?: number | null;
            points: components["schemas"]["MetricPoint"][];
            extensions?: {
                [key: string]: unknown;
            };
        };
        MetricsResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["MetricsData"];
        };
        User: {
            username: string;
            permission: components["schemas"]["PermissionType"];
            /** Format: date-time */
            created_at: string;
            extensions?: {
                [key: string]: unknown;
            };
        };
        UserListData: {
            items: components["schemas"]["User"][];
            extensions?: {
                [key: string]: unknown;
            };
        };
        UserListResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["UserListData"];
        };
        UpdatePermissionRequest: {
            permission: components["schemas"]["PermissionType"];
            extensions?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required or session expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Permission denied. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource already exists or state conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        DeviceUUID: string;
        Username: string;
        /**
         * @description Auth status filter:
         *     - authenticated -> `AuthenticateStatus=0`
         *     - refused -> `AuthenticateStatus=1`
         *     - pending -> `AuthenticateStatus=2`
         *     - revoked -> `AuthenticateStatus=4`
         *     - all -> no filter
         */
        DeviceStatusFilter: "all" | "authenticated" | "pending" | "refused" | "revoked";
        Page: number;
        Size: number;
        MetricsRange: "1h" | "6h" | "24h" | "7d" | "all";
        /** @description Explicit start timestamp in milliseconds. Overrides range when paired with end_ms. */
        StartMs: number;
        /** @description Explicit end timestamp in milliseconds. Overrides range when paired with start_ms. */
        EndMs: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCaptchaConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Captcha configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaConfigResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in successfully. */
            200: {
                headers: {
                    /** @description Session cookie set by server. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: {
                /**
                 * @description Auth status filter:
                 *     - authenticated -> `AuthenticateStatus=0`
                 *     - refused -> `AuthenticateStatus=1`
                 *     - pending -> `AuthenticateStatus=2`
                 *     - revoked -> `AuthenticateStatus=4`
                 *     - all -> no filter
                 */
                status?: components["parameters"]["DeviceStatusFilter"];
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    approveDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked/Rejected. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    unblockDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unblocked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    refreshDeviceToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token refreshed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getMetrics: {
        parameters: {
            query?: {
                range?: components["parameters"]["MetricsRange"];
                /** @description Explicit start timestamp in milliseconds. Overrides range when paired with end_ms. */
                start_ms?: components["parameters"]["StartMs"];
                /** @description Explicit end timestamp in milliseconds. Overrides range when paired with start_ms. */
                end_ms?: components["parameters"]["EndMs"];
            };
            header?: never;
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metric points. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateUserPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePermissionRequest"];
            };
        };
        responses: {
            /** @description Permission updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
