/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/captcha/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取前端验证码服务配置。 */
        get: operations["getCaptchaConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注册用户账号。
         * @description 与现有注册行为保持一致：
         *     - 首个注册用户获得 `Admin` 权限。
         *     - 后续用户默认获得 `None` 权限。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录并创建认证会话。 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出当前会话。 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前已认证用户信息。 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按认证状态列出设备。 */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取设备详情。 */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /** 永久删除设备及其关联数据。 */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 审批待认证设备。 */
        post: operations["approveDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 拒绝待认证设备或撤销已认证设备。 */
        post: operations["revokeDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将设备从已拒绝/已撤销状态移回待认证状态。 */
        post: operations["unblockDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新设备令牌。 */
        post: operations["refreshDeviceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{uuid}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将下行指令推入设备发送队列。 */
        post: operations["enqueueDeviceCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询设备指标点数据。 */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出系统用户。 */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{username}/permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新用户权限等级。 */
        post: operations["updateUserPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseBase: {
            /**
             * @description 0 表示成功，非 0 表示错误。
             * @example 0
             */
            code: number;
            /** @example ok */
            message: string;
            /**
             * @description 用于链路追踪的关联 ID。
             * @example req_20260312_abcdef
             */
            request_id: string;
            /** @description 可扩展元数据。 */
            meta?: {
                [key: string]: unknown;
            };
        };
        ErrorDetail: {
            /** @example validation_error */
            type: string;
            field?: string | null;
            reason?: string | null;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: components["schemas"]["ApiResponseBase"] & {
            data?: null;
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * @description 0=无权限, 1=只读, 2=读写, 3=管理员
         * @enum {integer}
         */
        PermissionType: 0 | 1 | 2 | 3;
        /**
         * @description 0=已认证, 1=已拒绝, 2=待认证, 3=未知, 4=已撤销
         * @enum {integer}
         */
        AuthStatusType: 0 | 1 | 2 | 3 | 4;
        /**
         * @description 0=离线, 1=在线, 2=延迟
         * @enum {integer}
         */
        DeviceRuntimeStatus: 0 | 1 | 2;
        /**
         * @description 1=温度, 2=湿度, 4=光照
         * @enum {integer}
         */
        MetricType: 1 | 2 | 4;
        CaptchaConfig: {
            /** @enum {string} */
            provider: "none" | "turnstile";
            enabled: boolean;
            site_key?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        CaptchaConfigResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["CaptchaConfig"];
        };
        RegisterRequest: {
            username: string;
            password: string;
            /** Format: email */
            email?: string | null;
            captcha_token?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            username: string;
            password: string;
            /** @default false */
            remember_me: boolean;
            captcha_token?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        AuthSession: {
            username: string;
            email?: string | null;
            permission: components["schemas"]["PermissionType"];
            /** @description 当前生效租户（由 `X-Tenant-Id` 或服务端默认策略解析）。 */
            active_tenant?: string;
            /** @default true */
            authenticated: boolean;
            extensions?: {
                [key: string]: unknown;
            };
        };
        AuthSessionResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["AuthSession"];
        };
        DeviceMetadata: {
            name: string;
            hw_version: string;
            sw_version: string;
            config_version: string;
            sn: string;
            mac: string;
            /** Format: date-time */
            created_at: string;
            token?: string | null;
            authenticate_status: components["schemas"]["AuthStatusType"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceRuntime: {
            status?: components["schemas"]["DeviceRuntimeStatus"];
            /** @enum {string} */
            status_text?: "offline" | "online" | "delayed";
            /** Format: int64 */
            last_seen_ms?: number | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceRecord: {
            uuid: string;
            meta: components["schemas"]["DeviceMetadata"];
            runtime?: components["schemas"]["DeviceRuntime"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        PageMeta: {
            page: number;
            size: number;
            returned: number;
            total?: number | null;
            has_next?: boolean | null;
        };
        DeviceListData: {
            items: components["schemas"]["DeviceRecord"][];
            page: components["schemas"]["PageMeta"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceListResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["DeviceListData"];
        };
        DeviceDetailResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["DeviceRecord"];
        };
        ActionResult: {
            /** @example approve_device */
            action: string;
            /** @example 07f5e... */
            target: string;
            /** @default true */
            success: boolean;
            extensions?: {
                [key: string]: unknown;
            };
        };
        ActionResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["ActionResult"];
        };
        RefreshTokenData: {
            uuid: string;
            token: string;
            /** Format: date-time */
            rotated_at?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        RefreshTokenResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["RefreshTokenData"];
        };
        /**
         * @description 设备下行指令名称。
         * @enum {string}
         */
        DeviceCommandName: "config_push" | "ota_data" | "action_exec" | "screen_wy";
        /**
         * @description 设备下行指令状态。
         * @enum {string}
         */
        DeviceCommandStatus: "queued" | "sent" | "acked" | "failed";
        DeviceCommandRequest: {
            command: components["schemas"]["DeviceCommandName"];
            /** @description 指令负载（原样转发给设备侧）。 */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        DeviceCommandEnqueueData: {
            /** Format: int64 */
            command_id: number;
            uuid: string;
            command: components["schemas"]["DeviceCommandName"];
            /**
             * @description 协议 CmdID 的十进制表示。
             * @example 515
             */
            cmd_id: number;
            status: components["schemas"]["DeviceCommandStatus"];
            /** Format: date-time */
            enqueued_at?: string | null;
            extensions?: {
                [key: string]: unknown;
            };
        };
        DeviceCommandEnqueueResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["DeviceCommandEnqueueData"];
        };
        MetricPoint: {
            /**
             * Format: int64
             * @description Unix 时间戳（毫秒）。
             */
            ts: number;
            /** Format: float */
            value: number;
            type: components["schemas"]["MetricType"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        MetricsData: {
            uuid: string;
            /** @enum {string|null} */
            range?: "1h" | "6h" | "24h" | "7d" | "all" | null;
            /** Format: int64 */
            start_ms?: number | null;
            /** Format: int64 */
            end_ms?: number | null;
            points: components["schemas"]["MetricPoint"][];
            extensions?: {
                [key: string]: unknown;
            };
        };
        MetricsResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["MetricsData"];
        };
        User: {
            username: string;
            permission: components["schemas"]["PermissionType"];
            /** Format: date-time */
            created_at: string;
            extensions?: {
                [key: string]: unknown;
            };
        };
        UserListData: {
            items: components["schemas"]["User"][];
            extensions?: {
                [key: string]: unknown;
            };
        };
        UserListResponse: components["schemas"]["ApiResponseBase"] & {
            data: components["schemas"]["UserListData"];
        };
        UpdatePermissionRequest: {
            permission: components["schemas"]["PermissionType"];
            extensions?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 无效请求。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 需要认证或会话已过期。 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 权限不足。 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在。 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源已存在或状态冲突。 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        DeviceUUID: string;
        Username: string;
        /**
         * @description 认证状态筛选：
         *     - authenticated -> `AuthenticateStatus=0`
         *     - refused -> `AuthenticateStatus=1`
         *     - pending -> `AuthenticateStatus=2`
         *     - revoked -> `AuthenticateStatus=4`
         *     - all -> 不筛选
         */
        DeviceStatusFilter: "all" | "authenticated" | "pending" | "refused" | "revoked";
        Page: number;
        Size: number;
        MetricsRange: "1h" | "6h" | "24h" | "7d" | "all";
        /** @description 显式指定开始时间戳（毫秒）。与 `end_ms` 同时提供时会覆盖 `range`。 */
        StartMs: number;
        /** @description 显式指定结束时间戳（毫秒）。与 `start_ms` 同时提供时会覆盖 `range`。 */
        EndMs: number;
        /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
        TenantHeader: string;
        /** @description 设备分组过滤参数（当前阶段仅保留契约位，后续实现组级过滤）。 */
        GroupID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCaptchaConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 验证码配置。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaConfigResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功。 */
            200: {
                headers: {
                    /** @description 由服务端设置的会话 Cookie。 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已登出。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户信息。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: {
                /**
                 * @description 认证状态筛选：
                 *     - authenticated -> `AuthenticateStatus=0`
                 *     - refused -> `AuthenticateStatus=1`
                 *     - pending -> `AuthenticateStatus=2`
                 *     - revoked -> `AuthenticateStatus=4`
                 *     - all -> 不筛选
                 */
                status?: components["parameters"]["DeviceStatusFilter"];
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                /** @description 设备分组过滤参数（当前阶段仅保留契约位，后续实现组级过滤）。 */
                group_id?: components["parameters"]["GroupID"];
            };
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    approveDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已通过审批。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销/已拒绝。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    unblockDevice: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已解除阻断。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    refreshDeviceToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 令牌已刷新。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    enqueueDeviceCommand: {
        parameters: {
            query?: never;
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCommandRequest"];
            };
        };
        responses: {
            /** @description 指令已入队。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCommandEnqueueResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getMetrics: {
        parameters: {
            query?: {
                range?: components["parameters"]["MetricsRange"];
                /** @description 显式指定开始时间戳（毫秒）。与 `end_ms` 同时提供时会覆盖 `range`。 */
                start_ms?: components["parameters"]["StartMs"];
                /** @description 显式指定结束时间戳（毫秒）。与 `start_ms` 同时提供时会覆盖 `range`。 */
                end_ms?: components["parameters"]["EndMs"];
            };
            header?: {
                /** @description 当前请求租户上下文。未传时后端回退为 `tenant_legacy`。 */
                "X-Tenant-Id"?: components["parameters"]["TenantHeader"];
            };
            path: {
                uuid: components["parameters"]["DeviceUUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指标点数据。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateUserPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePermissionRequest"];
            };
        };
        responses: {
            /** @description 权限已更新。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
